build-k8s-simple-file-server:
  script: 
    - echo "${HOSTNAME}" $(pwd) $(date)
    - ./build
    - bin/slack-status k8s-simple-file-server-build ${?}
    - ./dockerize
    - bin/slack-status k8s-simple-file-server-dockerize ${?}
  only:
    - master
  tags:
    - shell
    - ssh
