stages:
  - build
  - deploy

variables:
  ########################################################################
  # Enable the internal registry certificate location which is provided in
  # the secrets for the builder
  ########################################################################
  GIT_SSL_NO_VERIFY: "1"
  GIT_SSL_CAINFO:    "${HOME}/.private/gitlab.crt"

build-k8s-simple-file-server:
  stage: build
  script:
    - |
      set +x
      env
      curl -s -o env http://k8s-secrets-service/env
      # configure environment from secrets service
      . ./env
      curl -s -o slack.sh ${slack};
      chmod +x slack.sh
      export GOPATH=/go
      export PATH=${GOPATH}/bin:${PATH}:${PWD}
      echo "${HOSTNAME}" $(pwd) $(date)
      step=build
      ./build
      rc=$?
      if (( debug )); then echo ./slack.sh --step=${step} --gitlab-host=${gitlab_host} --gitlab-port=${gitlab_port} --gitlab-user=${gitlab_user} --slack-url=${config_url} --rc=${?}; fi
      ./slack.sh --step=${step} --gitlab-host=${gitlab_host} --gitlab-port=${gitlab_port} --gitlab-user=${gitlab_user} --slack-url=${config_url} --rc=${?}

  only:
    # v0.0.0
    - /^v[0-9]*\.[0-9]*\.[0-9]*$/
    # release-0.0
    - /^release-[0-9]*\.[0-9]*$/
    # prod-0.0
    - /^prod-[0-9]*\.[0-9]*$/
    # issue-any....text...-#[0-9]*
    - /^issue-.*-#[0-9]*$/
    # canary-0.0
    - /^canary-[0-9]*\.[0-9]*$/
    # # wip-0.0
    # - /^wip-[0-9]*\.[0-9]$/
    - release
    - release/\/.*/
    - canary/\/.*/
    - canary
    - prod/\/.*/
    - prod
    # - wip/*
    # - wip
  except:
    - master
    - /^wip-[0-9]*\.[0-9]$/
    - wip/*
    - wip

  tags:
    - shell
    - ssh

deploy-k8s-simple-file-server:
  stage: deploy
  script:
    - |
      set +x
      env
      curl -s -o env http://k8s-secrets-service/env
      # configure environment from secrets service
      . ./env
      curl -s -o slack.sh ${slack};
      chmod +x slack.sh
      export GOPATH=/go
      export PATH=${GOPATH}/bin:${PATH}:${PWD}
      echo "${HOSTNAME}" $(pwd) $(date)
      step=dockerize
      ./dockerize
      rc=$?
      if (( debug )); then echo ./slack.sh --step=${step} --gitlab-host=${gitlab_host} --gitlab-port=${gitlab_port} --gitlab-user=${gitlab_user} --slack-url=${config_url} --rc=${?}; fi
      ./slack.sh --step=${step} --gitlab-host=${gitlab_host} --gitlab-port=${gitlab_port} --gitlab-user=${gitlab_user} --slack-url=${config_url} --rc=${?}

  # artifacts:
  #   untracked: true
  #   paths:
  #   - bin/

  only:
    # v0.0.0
    - /^v[0-9]*\.[0-9]*\.[0-9]*$/
    # release-0.0
    - /^release-[0-9]*\.[0-9]*$/
    # issue-any....text...-#[0-9]*
    - /^issue-.*-#[0-9]*$/
    # canary-0.0
    - /^canary-[0-9]*\.[0-9]*$/
    # # wip-0.0
    # - /^wip-[0-9]*\.[0-9]$/
    - release
    - release/\/.*/
    - canary/\/.*/
    - canary
    - prod/\/.*/
    - prod
    # - wip/*
    # - wip
  except:

    - master
    - /^wip-[0-9]*\.[0-9]$/
    - wip/*
    - wip

  tags:
    - shell
    - ssh
