stages:
  - build
  
variables:
  gitlab_user: "root"
  gitlab_host: "128.107.15.211"
  gitlab_port: "8888"
  config_url:  "http://ci-secret-config/slack.url"
  secret_url:  "http://ci-secret-config/kubeconfig"
  deploy_yaml: "http://ci-secret-config/deploy.yaml"
  debug:       "0"
  registry:    "k8s-docker-registry:5000"

build-k8s-simple-file-server:
  stage: build
  script: 
    - echo "${HOSTNAME}" $(pwd) $(date)
    - ./build
    - bin/slack-status k8s-simple-file-server-build ${?}
    - ./dockerize
    - bin/slack-status k8s-simple-file-server-dockerize ${?}
  only:
    - master
  tags:
    - shell
    - ssh
