#!/bin/bash
dir=$(dirname $(readlink -f ${0}))
cd ${dir}
name=${dir##*/}
cat > Dockerfile <<EOF
FROM centos:latest
COPY bin/${name} /${name}
CMD [ "/${name}" ]
EOF

image=${name}:latest
registry=${registry:-k8s-docker-registry:5000}
target=${registry}/${image}
if docker build --force-rm --rm --tag ${image} . ; then
    docker tag -f ${image} ${target}
    docker push ${target}
fi
